[package]
name = "dorimubot-commands"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Command runtime support for DorimuBot Framework"

[dependencies]
dorimubot-framework-core = { path = "../dorimubot-framework-core" }
dorimubot-commands-macros = { path = "../dorimubot-commands-macros" }
inventory.workspace = true
qqbot-rust-sdk = { workspace = true, features = ["events", "openapi"] }
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
