[package]
name = "dorimubot-axum"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Axum integration for DorimuBot Framework"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
dorimubot-framework-core = { path = "../dorimubot-framework-core" }
qqbot-rust-sdk = { workspace = true, features = ["events"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
