[package]
name = "dorimubot-framework"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "All-in-one facade for DorimuBot Framework"

[dependencies]
dorimubot-framework-core = { path = "../dorimubot-framework-core" }
dorimubot-axum = { path = "../dorimubot-axum" }
dorimubot-commands = { path = "../dorimubot-commands" }
dorimubot-commands-macros = { path = "../dorimubot-commands-macros" }

[dev-dependencies]
qqbot-rust-sdk = { workspace = true, features = ["openapi"] }
tokio.workspace = true
